In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
from utils import *
import traceback
import sys
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
num_images = 113

for i in range(1, num_images+1):
  for j in range(i+1, min(num_images+1, i+5)):

    im1 = load_image('img{}.jpg'.format(i), path = '../data/lettuce_home/set6/')
    im2 = load_image('img{}.jpg'.format(j), path = '../data/lettuce_home/set6/')
      
    try:
      final_img = match_sift_double_iter_compare(im1, im2)
      if final_img is None:
        continue
      
      
      cv2.imwrite('../result/lettuce_home/sift_matching/set6/{}_{}.jpg'.format(i,j), final_img)

      #plt.imshow(match_2_3),plt.show()
    except:
      traceback.print_exc(file=sys.stdout)
      pass
    

selected points with ratio:  80
[[ 0.0779623  -0.60034537  0.34103402]
 [ 0.64519867 -0.00229809 -0.22261852]
 [-0.19328551  0.1181927  -0.00535724]]
[[-0.06292087  0.53791597 -0.35368205]
 [-0.58207214  0.03246776  0.33262274]
 [ 0.24280946 -0.2648774   0.04449593]]
selected points with ratio:  49
[[ 0.02409841  0.34006614  0.25829044]
 [-0.32211427 -0.09607403 -0.53511758]
 [-0.30897988  0.561296   -0.08485236]]
[[-0.02463961 -0.33967431 -0.26081379]
 [ 0.3212042   0.09657961  0.533865  ]
 [ 0.31163948 -0.56046119  0.08510535]]
selected points with ratio:  13
[[-0.3507614  -0.11882945 -0.60235255]
 [ 0.16460883  0.42547388 -0.17625297]
 [ 0.16890153  0.4432907  -0.1891926 ]]
[[ 0.13056103 -0.53309782  0.36935686]
 [ 0.58804261  0.19852934  0.24019852]
 [-0.17493043 -0.29265284  0.05644793]]
selected points with ratio:  14
[[ 0.03976251  0.56889758 -0.35915212]
 [-0.54176127 -0.06743531  0.09489624]
 [ 0.44891244 -0.18019655  0.06879663]]
[[-0.03834816 -0.55449005  0.36605085]
 [ 0.53

selected points with ratio:  9
[[-0.0305981   0.59157568 -0.12189424]
 [-0.69780939 -0.05458982 -0.10034751]
 [-0.01447695  0.35871837 -0.07326458]]
[[ 0.03062555 -0.59154519  0.12189945]
 [ 0.6978014   0.05462308  0.10038438]
 [ 0.01447845 -0.35876201  0.07327735]]
selected points with ratio:  15
[[-0.11376215  0.54294527 -0.27779635]
 [ 0.69210978  0.13358432  0.03297623]
 [-0.01170797  0.30747682 -0.14990188]]
[[ 0.50777515 -0.47180847 -0.07101483]
 [-0.47927006 -0.43763818 -0.21670367]
 [-0.0360785  -0.2002912  -0.07008845]]
selected points with ratio:  113
[[-0.03231571 -0.04710154  0.49626097]
 [ 0.08062278 -0.00735894 -0.49653942]
 [-0.46460973  0.52960435 -0.03183761]]
[[-0.05064614 -0.03191334  0.50035921]
 [ 0.06858735  0.01088057 -0.49155604]
 [-0.47498934  0.52231037 -0.03441258]]
selected points with ratio:  78
[[ 0.08205182 -0.32933012  0.06260546]
 [ 0.45460299  0.03174031 -0.54055551]
 [-0.16174217  0.5881952  -0.09425509]]
[[-0.08601574  0.33911588 -0.0586128 ]
 [-0.45

selected points with ratio:  34
[[-0.00367621 -0.1628281   0.55568464]
 [ 0.15435126 -0.0738476  -0.41796419]
 [-0.41618429  0.53611086  0.00959232]]
[[-0.00590765 -0.17516408  0.55060001]
 [ 0.16303473 -0.07596568 -0.42121181]
 [-0.40887963  0.53761087  0.01199079]]
selected points with ratio:  49
[[-0.03316052 -0.02466662 -0.47947221]
 [ 0.02679905  0.04327058  0.51572667]
 [ 0.33255388 -0.62346815  0.02300425]]
[[-0.02084466 -0.03892963 -0.49508506]
 [ 0.02330402  0.0356081   0.50113797]
 [ 0.35664075 -0.60984383  0.02980557]]
selected points with ratio:  31
[[-0.00959577  0.09193559 -0.15909235]
 [-0.16938546  0.07674356 -0.66149709]
 [ 0.27996489  0.64427794  0.02261813]]
[[-0.04501828 -0.04175464 -0.15705024]
 [-0.09336493  0.07165168 -0.67930958]
 [ 0.26536684  0.65230581  0.01817213]]
selected points with ratio:  8
[[ 0.05240557  0.60158561 -0.3467162 ]
 [ 0.41270367 -0.0361464   0.19133016]
 [ 0.52196582  0.12399688  0.13811097]]
[[ 0.05130348  0.60040581 -0.34970477]
 [ 0.409

selected points with ratio:  93
[[ 0.10536909  0.14830735  0.58783708]
 [-0.10640395 -0.00934722 -0.34036708]
 [-0.36758797  0.5978449  -0.03938902]]
[[-0.09951176 -0.15165409 -0.58290157]
 [ 0.11533302 -0.0053827   0.35082902]
 [ 0.35703528 -0.60170724  0.03723896]]
selected points with ratio:  85
[[-0.02060346 -0.17172196 -0.34710924]
 [ 0.143809   -0.02265702 -0.59604342]
 [ 0.38274593  0.57093752 -0.02600039]]
[[-0.02102023 -0.17046085 -0.34601395]
 [ 0.14121384 -0.02139855 -0.59746272]
 [ 0.37965244  0.57322194 -0.02636797]]
selected points with ratio:  15
[[ 0.09623753  0.14279692 -0.19911819]
 [ 0.35141953  0.06506272 -0.56250087]
 [-0.17168736  0.67579732  0.01961337]]
[[ 0.0721036  -0.69928553 -0.05069736]
 [ 0.66831327  0.07168998 -0.1797495 ]
 [-0.11564654 -0.0703567   0.02853841]]
selected points with ratio:  211
[[-0.10986302 -0.25876431 -0.64768343]
 [ 0.15667977 -0.10326237 -0.02575   ]
 [ 0.59829768 -0.32568577  0.03963912]]
[[-0.11083029 -0.24483422 -0.65399233]
 [ 0.1

selected points with ratio:  8
[[ 0.30949316  0.37712565 -0.08075753]
 [ 0.59529728 -0.29576287 -0.17001236]
 [ 0.11774631  0.51981219 -0.02531444]]
[[ 0.27749262  0.62642356  0.13245671]
 [-0.648568    0.25584243  0.10803428]
 [ 0.00150712  0.12013511  0.02906314]]
selected points with ratio:  221
[[ 0.00789708 -0.18881186 -0.11894735]
 [ 0.19039334 -0.01121866 -0.66949652]
 [ 0.09872941  0.6748922  -0.01764065]]
[[ 0.00420783 -0.19596768 -0.10689524]
 [ 0.18820471 -0.00810747 -0.67250292]
 [ 0.09288559  0.67348393 -0.01403931]]
selected points with ratio:  66
[[ 0.01222789 -0.13494779 -0.21548076]
 [ 0.15951912 -0.02278057 -0.65218952]
 [ 0.21375614  0.66182305 -0.01377319]]
[[ 0.01425817 -0.13436128 -0.21209204]
 [ 0.16539352 -0.02395328 -0.65171061]
 [ 0.21070645  0.66297765 -0.01298628]]
selected points with ratio:  20
[[-0.011545   -0.05956161 -0.12952774]
 [ 0.07496744  0.01224203 -0.69144312]
 [ 0.26646756  0.65105299  0.0283401 ]]
[[ 0.20935998  0.67095636  0.02798427]
 [-0.66

selected points with ratio:  15
[[ 0.12546567  0.57960189  0.23093747]
 [ 0.60135117 -0.048871   -0.351764  ]
 [-0.16790519 -0.27640476 -0.05144552]]
[[ 0.48871927 -0.48185851 -0.17017514]
 [ 0.49140464  0.41276463  0.2399099 ]
 [ 0.12365924  0.10713215  0.06186635]]
selected points with ratio:  19
[[-0.03224669 -0.00467077  0.38496331]
 [ 0.02454989  0.05056354 -0.59019382]
 [-0.35270095  0.6119305   0.01991411]]
[[-0.03224644 -0.00374351  0.38590743]
 [ 0.02323526  0.05099102 -0.58965994]
 [-0.35345378  0.61142808  0.02022214]]
selected points with ratio:  15
[[ 0.06504223 -0.04356962 -0.59137574]
 [ 0.06421406 -0.05239227  0.38708327]
 [ 0.55614996 -0.42157995  0.02028926]]
[[ 0.10394701  0.59093071 -0.06898294]
 [-0.61996524  0.02105394 -0.32996629]
 [-0.01848721  0.36577062 -0.08619411]]
selected points with ratio:  10
[[ 0.4809519  -0.45500451 -0.14558407]
 [ 0.48692173  0.48405471 -0.09631361]
 [-0.04379856  0.23935552  0.02395876]]
[[ 0.47668692 -0.47569951  0.21474719]
 [-0.31

[[-0.46339216  0.52219403  0.05727695]
 [ 0.50363609  0.42871651 -0.159026  ]
 [ 0.07801249  0.1976877  -0.03738518]]
[[ 0.41441389 -0.56703109 -0.05291874]
 [ 0.51700153  0.41217851 -0.09091841]
 [ 0.22086075  0.09134252 -0.03695534]]
selected points with ratio:  40
[[ 0.03972904  0.33206213 -0.61659234]
 [-0.40362223  0.03320384 -0.09101036]
 [ 0.57873349  0.0262415  -0.0072717 ]]
[[ 0.03746984  0.32616755 -0.62136993]
 [-0.40060539  0.03344513 -0.0791011 ]
 [ 0.58133952  0.0154675  -0.00741882]]
selected points with ratio:  35
[[-0.67039517  0.15176175 -0.03399338]
 [-0.09308471 -0.5788165   0.32529925]
 [ 0.19955448  0.16204192 -0.1038781 ]]
[[-0.56737316 -0.002714   -0.27241008]
 [-0.02611494 -0.32900472  0.50079386]
 [ 0.3808551   0.24534682 -0.19724814]]
selected points with ratio:  82
[[-0.02129859 -0.27949157  0.28023698]
 [ 0.19872919 -0.03051096 -0.61432892]
 [-0.16255797  0.62986111  0.04386023]]
[[-0.02104672 -0.27817024  0.28216534]
 [ 0.20059573 -0.03028078 -0.61295426]


selected points with ratio:  134
[[-8.62481912e-03 -3.40789127e-02  2.25338494e-02]
 [ 1.16682456e-01 -3.41786628e-04 -6.97011681e-01]
 [ 9.67086592e-02  6.99409906e-01  1.70143379e-02]]
[[-0.00866239 -0.03860282  0.01885666]
 [ 0.11914841 -0.0021716  -0.69670696]
 [ 0.09573436  0.69934119  0.01531012]]
selected points with ratio:  15
[[-0.07502797 -0.0295113   0.0604658 ]
 [-0.34611242  0.16039216  0.58980639]
 [-0.40923906 -0.56572305 -0.09451754]]
[[-0.32392279 -0.56945793 -0.06620319]
 [ 0.52986485 -0.34164584  0.32011963]
 [-0.13216162 -0.21940005 -0.0291642 ]]
selected points with ratio:  19
[[ 0.19525534  0.63074571  0.01375194]
 [-0.58325482  0.21720603 -0.3274259 ]
 [ 0.14064743  0.21845788  0.04204968]]
[[ 0.28690712  0.63300637 -0.12371662]
 [-0.61946478  0.25353699 -0.06711739]
 [ 0.1835033  -0.12093392  0.02933588]]
selected points with ratio:  8
[[ 0.61916636  0.27452229  0.03490905]
 [ 0.21667562 -0.5232603   0.42256216]
 [ 0.17444035  0.10137521 -0.00608829]]
[[-0.70116

selected points with ratio:  19
[[-0.08220719  0.02123848  0.3118625 ]
 [ 0.11848998  0.10297689 -0.61283261]
 [-0.20870564  0.67110735  0.03717036]]
[[-0.11388372  0.02153244  0.30812652]
 [ 0.16173904  0.12653972 -0.59676232]
 [-0.24103221  0.65900314  0.03075961]]
selected points with ratio:  19
[[ 0.09264651 -0.00500045 -0.2211285 ]
 [ 0.25812152 -0.00984842 -0.61300254]
 [ 0.18902576  0.67795529  0.06814592]]
[[ 0.0908573  -0.00211869 -0.21896659]
 [ 0.25480584 -0.00779874 -0.61547354]
 [ 0.18416622  0.67931878  0.06788508]]
selected points with ratio:  38
[[-0.02153945 -0.13372851  0.01942277]
 [ 0.19183483  0.0501068  -0.67785841]
 [ 0.06274233  0.68764745  0.07534295]]
[[ 0.123139    0.61702904  0.05676553]
 [-0.57790139  0.07126696  0.40094464]
 [-0.04916957 -0.31187777 -0.0373983 ]]
selected points with ratio:  53
[[ 0.03731214  0.21369024  0.02977376]
 [-0.22616891  0.11128789 -0.66062184]
 [ 0.10797378  0.65973555  0.07204088]]
[[-0.1024086  -0.63906183  0.08510268]
 [ 0.60

In [3]:
im1_idx = 1
im2_idx = 22
inp_path = '../data/lettuce_home/set4/'

im1 = load_image('img{}.jpg'.format(im1_idx), path = '../data/lettuce_home/set4/')
im2 = load_image('img{}.jpg'.format(im2_idx), path = '../data/lettuce_home/set4/')