In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
from utils import *
import traceback
import sys
%load_ext autoreload
%autoreload 2

In [2]:
num_images = 24

for i in range(1, num_images+1):
  for j in range(i+1, num_images+1):

    im1 = load_image('img{}.jpg'.format(i), path = '../data/lettuce_home/set4/')
    im2 = load_image('img{}.jpg'.format(j), path = '../data/lettuce_home/set4/')
      
    try:
      final_img = match_sift_double_iter(im1, im2)
      if final_img is None:
        continue
      
      
      cv2.imwrite('../result/lettuce_home/sift_matching/set4/alt_all/{}_{}.jpg'.format(i,j), final_img)

      #plt.imshow(match_2_3),plt.show()
    except:
      traceback.print_exc(file=sys.stdout)
      pass
    

selected points with ratio:  15
[[ 0.29935612  0.23026362  0.03370398]
 [-0.15028998 -0.06537325 -0.67373326]
 [ 0.44722804  0.36373923 -0.20768299]]
[[-0.58774794 -0.35778789  0.11879138]
 [ 0.30959462 -0.60122253 -0.17289454]
 [ 0.14590934 -0.0407906  -0.04759732]]
selected points with ratio:  15
[[ 0.26981571  0.30396529 -0.04876047]
 [-0.13644919 -0.06304028 -0.68985954]
 [ 0.36876625  0.42406146 -0.13457965]]
[[ 0.2195071   0.02733546 -0.54950495]
 [-0.38125928 -0.1185883  -0.43308548]
 [ 0.52582446  0.12801382 -0.09617666]]
selected points with ratio:  24
[[-0.04214786  0.36340863  0.27017393]
 [-0.03261283  0.10055466 -0.65106147]
 [-0.08264686  0.59039048 -0.05211986]]
[[-0.06394469 -0.65330177 -0.2069819 ]
 [ 0.64234474 -0.06375998 -0.17622147]
 [ 0.24218426  0.1406382  -0.01038975]]
selected points with ratio:  17
[[-0.12152771  0.3400078   0.27089397]
 [-0.22089531 -0.0106528  -0.61732385]
 [-0.34066563  0.49830164 -0.04344675]]
[[ 0.19771585 -0.64489352 -0.2120438 ]
 [ 0.64

/home/ayush/dev/4d_crops/opencv_sfm/code/utils.py:89: RuntimeWarning: divide by zero encountered in true_divide
  distances_right = np.abs(np.sum(np.multiply(right_epipolar_lines, test_set_im1), axis=1)/line_dist_normalizer_right)


[[-0.14793714 -0.42942512 -0.42587142]
 [ 0.27168651 -0.10130993  0.40364417]
 [ 0.23726886 -0.53108512  0.16428151]]
[[-0.3392781  -0.51186405 -0.17019011]
 [ 0.40805413 -0.19906884  0.41445419]
 [ 0.0724397  -0.42489023  0.17387586]]
selected points with ratio:  16
[[-0.06622476  0.03828288 -0.21743805]
 [-0.22369167  0.0152551  -0.63061457]
 [ 0.20626904  0.67405684 -0.04499382]]
[[-0.0791155  -0.63815915 -0.15866664]
 [ 0.60853753 -0.12390057 -0.21385624]
 [ 0.29419491  0.20641864 -0.0274858 ]]
selected points with ratio:  10
[[-2.41030286e-01  1.98338374e-01 -4.30832180e-01]
 [-1.84652672e-01  2.02553726e-01 -3.77745819e-01]
 [ 4.81606160e-01  5.16903068e-01  3.52062408e-04]]
[[ 0.09275629 -0.6170435  -0.09502646]
 [ 0.6385707   0.05632089 -0.25613247]
 [ 0.11141537  0.33533419 -0.01458561]]
selected points with ratio:  164
[[-0.00170739  0.12980216 -0.69456771]
 [-0.06284618 -0.01254999  0.02507544]
 [ 0.69900715  0.08429348  0.01648862]]
[[-0.01207395  0.19498657 -0.679262  ]
 [

selected points with ratio:  111
[[ 0.03830251  0.00488524 -0.7047381 ]
 [ 0.08374354  0.01556505 -0.03815688]
 [ 0.68888737  0.12920179  0.04339533]]
[[ 0.09348455 -0.29997529 -0.59587728]
 [ 0.32845117  0.06764239 -0.1957073 ]
 [ 0.53815484  0.32304837  0.03844262]]
selected points with ratio:  13
[[-0.17182112  0.45137701 -0.33273121]
 [-0.4262423   0.0355412  -0.29848391]
 [ 0.39823554  0.47364294  0.03253848]]
[[ 0.35602402  0.53234989 -0.20253904]
 [-0.13997079  0.16030326  0.56940472]
 [ 0.04963747  0.30998533  0.28418824]]
selected points with ratio:  22
[[ 0.11293692 -0.35275504  0.1000041 ]
 [ 0.55456539 -0.11006254  0.3564606 ]
 [-0.19880684 -0.60082406 -0.07465865]]
[[-0.01086869 -0.66002624 -0.19571919]
 [ 0.66924777  0.01115578 -0.18474212]
 [ 0.1349851   0.15959658  0.0101247 ]]
selected points with ratio:  10


/home/ayush/dev/4d_crops/opencv_sfm/code/utils.py:89: RuntimeWarning: invalid value encountered in true_divide
  distances_right = np.abs(np.sum(np.multiply(right_epipolar_lines, test_set_im1), axis=1)/line_dist_normalizer_right)
/home/ayush/dev/4d_crops/opencv_sfm/code/utils.py:90: RuntimeWarning: invalid value encountered in less
  inlier_mask_right = distances_right<threshold


[[ 0.05237683 -0.46311961  0.53120872]
 [ 0.31305954  0.06472555 -0.00338011]
 [-0.62341923 -0.09265031 -0.03393343]]
[[ 0.06228293 -0.5941726  -0.25216137]
 [ 0.58407374  0.01945915 -0.24894068]
 [ 0.28791939  0.30493349 -0.01096063]]
selected points with ratio:  15
[[-0.20450426 -0.24983238 -0.60314674]
 [ 0.20313808 -0.03700944  0.14245692]
 [ 0.55548144 -0.39299803 -0.07771726]]
[[-0.28601963 -0.36928925 -0.53038786]
 [ 0.30636378 -0.17495938 -0.06924098]
 [ 0.53780467 -0.27371059 -0.08421236]]
selected points with ratio:  9
[[ 0.04470565  0.00666753  0.12828622]
 [-0.22253216 -0.09074797 -0.65104862]
 [-0.07763028  0.69938412 -0.06866527]]
[[-0.14037389 -0.61969637 -0.23481756]
 [-0.57295685 -0.07256192  0.2692958 ]
 [-0.24356223  0.17123396  0.21546147]]
selected points with ratio:  11
[[-0.04959763  0.22260278 -0.53974961]
 [-0.19677953  0.22050494  0.44719561]
 [ 0.30534827 -0.52504561  0.02048032]]
[[-0.34926528 -0.30193737 -0.42796645]
 [ 0.25890253 -0.22835936 -0.40228598]
 

In [3]:
im1_idx = 1
im2_idx = 22
inp_path = '../data/lettuce_home/set4/'

im1 = load_image('img{}.jpg'.format(im1_idx), path = '../data/lettuce_home/set4/')
im2 = load_image('img{}.jpg'.format(im2_idx), path = '../data/lettuce_home/set4/')