In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
from utils import *

In [2]:
num_images = 6

for i in range(1, num_images+1):
  for j in range(i+1, num_images+1):

    im1 = load_image('img{}.jpg'.format(i), path = '../data/lettuce_home/set1/')
    im2 = load_image('img{}.jpg'.format(j), path = '../data/lettuce_home/set1/')
      
    try:
      match_im1, match_im2 = match_sift_double_iter(im1, im2)
      
      cv2.imwrite('../result/lettuce_home/sift_matching/{}_{}.jpg'.format(i,j), match_im1)
      cv2.imwrite('../result/lettuce_home/sift_matching/{}_{}_alt.jpg'.format(i,j), match_im2)

      #plt.imshow(match_2_3),plt.show()
    except:
      print('exception')
    

selected points with ratio:  4
None
exception
selected points with ratio:  6
[[ 0.65433811  0.15566761  0.18987606]
 [ 0.16778712 -0.68159079 -0.05591629]
 [ 0.11661989 -0.03908521  0.02415184]]
total input to new:
677
Extra matching val
13
selected points with ratio:  1
None
exception
selected points with ratio:  5
[[-0.34502021  0.19287519 -0.46277738]
 [ 0.31262156  0.40504532  0.25801639]
 [-0.01190802 -0.53212319  0.13391792]
 [-0.43259602 -0.20574895 -0.51807862]
 [ 0.02519805 -0.47880379  0.21133525]
 [-0.01526202 -0.45372948  0.14652173]
 [-0.17651175 -0.64262969  0.07523925]
 [ 0.62346064 -0.1074986   0.30544884]
 [-0.01575128  0.22922095 -0.06213918]
 [-0.25746042 -0.6493955  -0.04406323]
 [ 0.57470532 -0.23966665  0.32817028]
 [-0.01875212  0.11675903 -0.02552834]
 [-0.1923444  -0.63292889  0.10511857]
 [-0.60889389  0.14282078 -0.32813779]
 [ 0.09637666  0.2070973  -0.01878899]
 [-0.37428363 -0.58976577 -0.10405695]
 [-0.52860365  0.38531806 -0.24514019]
 [ 0.10209539 -0.03

In [3]:
import ngransac

ImportError: /home/ayush/miniconda3/lib/python3.7/site-packages/ngransac-0.0.0-py3.7-linux-x86_64.egg/ngransac.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E