In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
from utils import *
import traceback
import sys
%load_ext autoreload
%autoreload 2

In [2]:
num_images = 24

for i in range(1, num_images+1):
  for j in range(i+1, num_images+1):

    im1 = load_image('img{}.jpg'.format(i), path = '../data/lettuce_home/set4/')
    im2 = load_image('img{}.jpg'.format(j), path = '../data/lettuce_home/set4/')
      
    try:
      final_img = match_sift_double_iter(im1, im2)
      if final_img is None:
        continue
      
      
      cv2.imwrite('../result/lettuce_home/sift_matching/set4/{}_{}.jpg'.format(i,j), final_img)

      #plt.imshow(match_2_3),plt.show()
    except:
      traceback.print_exc(file=sys.stdout)
      pass
    

selected points with ratio:  15
[[ 0.27173527  0.21948328  0.08014753]
 [-0.15745369 -0.03690325 -0.66674999]
 [ 0.44046627  0.40483615 -0.20724744]]
[[-0.57096814 -0.37223854  0.07645766]
 [ 0.30390482 -0.5790288  -0.22786743]
 [ 0.21119118 -0.02796891 -0.06817662]]
selected points with ratio:  15
[[ 0.26981571  0.30396529 -0.04876047]
 [-0.13644919 -0.06304028 -0.68985954]
 [ 0.36876625  0.42406146 -0.13457965]]
[[-0.08839269 -0.10126701  0.07958453]
 [ 0.15155854  0.06231208  0.68599418]
 [-0.46433814 -0.49386418  0.1365485 ]]
selected points with ratio:  24
[[-0.04354879  0.37289222  0.26836394]
 [-0.02445497  0.10363845 -0.65188192]
 [-0.07637     0.58482961 -0.05374598]]
[[ 0.03106319  0.56428617  0.14252973]
 [-0.55884585  0.03581775  0.40444619]
 [-0.1721049  -0.39174146  0.0071892 ]]
selected points with ratio:  17
[[-0.11889427  0.31019374  0.25901238]
 [-0.16365391  0.00913939 -0.63981127]
 [-0.32286731  0.52938256 -0.04292772]]
[[ 0.1166688  -0.32007707 -0.25542682]
 [ 0.18

selected points with ratio:  91
[[-0.00128202  0.37355266 -0.60037428]
 [-0.00427418 -0.00217176  0.00188112]
 [ 0.69353613  0.11765108  0.0717414 ]]
[[-0.02136865  0.4082798  -0.57663492]
 [-0.02520551  0.00576864 -0.0176752 ]
 [ 0.68933599  0.13811349  0.07143327]]
selected points with ratio:  10
[[ 0.05943761  0.3816312  -0.59212334]
 [ 0.15725035  0.00812352  0.03805513]
 [ 0.67629777  0.06932384  0.1085745 ]]
[[ 0.135673   -0.55205093 -0.32637957]
 [ 0.62227966  0.12979379 -0.17077299]
 [ 0.20717003  0.2986469   0.07041151]]
selected points with ratio:  21
[[-0.37160991 -0.20590589 -0.55691139]
 [ 0.10146317 -0.2023725  -0.1077303 ]
 [ 0.44546732 -0.49237541 -0.07502423]]
[[-0.4192047  -0.23891443 -0.49798557]
 [ 0.12654487 -0.26728609 -0.15192819]
 [ 0.45348982 -0.44239245 -0.08541637]]
selected points with ratio:  33
[[-0.00548058  0.09509139 -0.64373373]
 [-0.15368869  0.31556972  0.28219499]
 [ 0.24000428 -0.5580641   0.06825255]]
[[ 0.19087578  0.23512032 -0.53772606]
 [-0.22

selected points with ratio:  201
[[-0.2318178   0.40521959 -0.38325982]
 [-0.27770912  0.01700757 -0.34348308]
 [ 0.27726804  0.56883495  0.19830909]]
[[-0.1863074   0.40741334 -0.43718704]
 [-0.23459394  0.00489769 -0.33109365]
 [ 0.31369173  0.55174514  0.20165541]]
selected points with ratio:  43
[[-0.19898394  0.44270584 -0.49991463]
 [-0.02392207  0.08639412 -0.08178034]
 [ 0.48989125  0.46118716  0.21700467]]
[[-0.15817254  0.43374117 -0.52591176]
 [ 0.01111706  0.09167538 -0.06227017]
 [ 0.51442045  0.4338992   0.21204817]]
selected points with ratio:  14
[[-0.1930911   0.46889602 -0.48758529]
 [ 0.0129183   0.08048612 -0.03062326]
 [ 0.46023368  0.46181822  0.2691452 ]]
[[-0.04656924  0.41294634 -0.57108031]
 [ 0.05720065  0.07623423  0.00842698]
 [ 0.46645479  0.43948739  0.28511417]]
selected points with ratio:  189
[[ 0.07264188 -0.09822097 -0.69647363]
 [ 0.17385976  0.03157589  0.01315641]
 [ 0.67145297  0.12228255  0.05292286]]
[[ 0.02211972  0.14715824 -0.69107407]
 [ 0.

In [3]:
im1_idx = 1
im2_idx = 22
inp_path = '../data/lettuce_home/set4/'

im1 = load_image('img{}.jpg'.format(im1_idx), path = '../data/lettuce_home/set4/')
im2 = load_image('img{}.jpg'.format(im2_idx), path = '../data/lettuce_home/set4/')